dataset_path: "path/to/your/dataset"  # Update this with the actual path in Google Drive
batch_size: 32
num_epochs: 50
learning_rate: 0.001
image_size: [224, 224]  # Adjust based on your model requirements
num_classes: 10  # Update this based on the number of classes in your dataset
train_split: 0.8  # Proportion of data to use for training
val_split: 0.1  # Proportion of data to use for validation
test_split: 0.1  # Proportion of data to use for testing
augmentation: true  # Set to true if you want to apply data augmentation
save_model_path: "models/fashion_cnn.h5"  # Path to save the trained model
load_model_path: "models/fashion_cnn.h5"  # Path to load the trained model for evaluation
logging: true  # Set to true if you want to log training metrics
log_dir: "logs/"  # Directory to save logs
visualization: true  # Set to true if you want to visualize results during training